### PR TITLE
Feature/backport s3 amazon fix

### PR DESCRIPTION
**Pull request by thanset**
This takes the recent s3 fix for ECS and back ports it for mesos 0.28.x. @aaronjwood If you want to take a look, it's very similar to the PR the other day.  Adding in proper signing headers for ECS and fixing how the backup/restore cycle works.

### CODE REVIEW

**Comment by aaronjwood** [comment]
I don't think these original changes worked in the cluster on the `development` or `feature/backport_s3_amazon_fix` branches. I saw some exception that got thrown when the state was trying to be persisted.

**Comment by aaronjwood** [comment]
Looks like you're missing the logging stuff from https://github.com/verizonlabs/dcos-cassandra-service/pull/12/files#diff-1383d7c19f8422fc5b7a562b7827d0b1R42

**Comment by aaronjwood** [comment]
Something seems off about this PR. It's showing that you added 2 commits to this on December 30, 2016.

**Comment by thanset** [comment]
@aaronjwood I think that's from my development VM being off, most likely

**Pull request merged**
